# Generated by Django 5.2.6 on 2025-11-10 20:46

import course.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_hr', models.PositiveIntegerField(default=1, help_text='จำนวนชั่วโมงรวม (เป็นจำนวนเต็ม)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_price', models.DecimalField(decimal_places=2, default=0, help_text='ราคามัดจำ', max_digits=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=course.models.course_cover_upload_path)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('training_days', models.JSONField(blank=True, default=list, help_text='ลิสต์วันในสัปดาห์')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('max_dogs', models.PositiveIntegerField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, help_text='รายการสิ่งที่จะได้รับ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.JSONField(blank=True, default=list)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='course.course')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'created_at'], name='course_cour_is_publ_c260fd_idx'),
        ),
        migrations.AddIndex(
            model_name='courseround',
            index=models.Index(fields=['course'], name='course_cour_course__cefd6c_idx'),
        ),
    ]
