# Generated by Django 5.2.6 on 2025-11-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainmydog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerapplication',
            name='intro',
            field=models.TextField(blank=True, help_text='แนะนำตัว/ประสบการณ์/เพิ่มเติมที่อยากเขียน', null=True),
        ),
    ]
