# Generated by Django 5.2.6 on 2025-11-19 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('trainmydog', '0002_alter_trainerapplication_intro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_full_name', models.CharField(default='', max_length=120)),
                ('owner_nickname', models.CharField(blank=True, default='', max_length=80)),
                ('owner_phone', models.CharField(default='', max_length=20)),
                ('dog_name', models.CharField(blank=True, default='', max_length=100)),
                ('dog_count', models.PositiveIntegerField(default=1)),
                ('dog_gender', models.CharField(blank=True, choices=[('male', 'ผู้'), ('female', 'เมีย')], default='', max_length=10)),
                ('dog_age_year', models.PositiveIntegerField(default=0)),
                ('dog_breed', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ'), ('canceled', 'ยกเลิกโดยผู้ใช้')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='course.course')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='course.courseround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
